[package]
name = "fvm_gas_calibration_shared"
description = "Filecoin Virtual Machine gas calibration"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"
authors = ["Protocol Labs", "Filecoin Core Devs"]
repository = "https://github.com/filecoin-project/ref-fvm"

[dependencies]
fvm_shared = { workspace = true, features = ["testing"] }
serde = { workspace = true }
serde_json = { workspace = true }
num-traits = { workspace = true }
num-derive = { workspace = true }
