[package]
name = "fvm_gas_calibration_shared"
description = "Filecoin Virtual Machine gas calibration"
version = "0.1.0"
edition.workspace = true
license.workspace = true
authors = ["Protocol Labs", "Filecoin Core Devs"]
repository.workspace = true

[dependencies]
fvm_shared = { workspace = true, features = ["testing"] }
serde = { workspace = true }
serde_json = { workspace = true }
num-traits = { workspace = true }
num-derive = { workspace = true }
