name: rust sccache
description: Shared Compilation Cache for Rust
inputs:
  version:
    description: The version of sccache to use
    required: true
  platform:
    description: The platform of sccache to use
    required: true
  key:
    description: An additional key for the cache
    required: false
  shared-key:
    description: An additional key that is stable over multiple jobs
    required: false
runs:
  using: composite
  steps:
    - id: rust
      name: Checking Rust version
      run: |
        version="$(rustc -vV)"
        echo "::set-output name=release::$(sed -En 's/^release: (.+)/\1/p' <<< "$version")"
        echo "::set-output name=host::$(sed -En 's/^host: (.+)/\1/p' <<< "$version")"
        echo "::set-output name=commit-hash::$(sed -En 's/^commit-hash: (.{0,12}).*/\1/p' <<< "$version")"
      shell: bash
    - id: platform
      name: Defining Platform to download
      run: |
        platform='unknown-linux-musl'
        if [[ ${{ inputs.platform }} == *"macos"* ]]; then
          platform='apple-darwin'
        fi
        echo "::set-output name=platform::$platform"
      shell: bash
    - id: cache
      name: Computing cache key
      run: |
        key='v0-sccache'
        if [[ ! -z '${{ inputs.shared-key }}' ]]; then
          key="$key-${{ inputs.shared-key }}"
        else
          if [[ ! -z '${{ inputs.key }}' ]]; then
            key="$key-${{ inputs.key }}"
          fi
          key="$key-${{ github.job }}"
        fi
        key="$key-${{ steps.rust.outputs.release }}-${{ steps.rust.outputs.host }}-${{ steps.rust.outputs.commit-hash }}"
        hash='${{ hashFiles('**/Cargo.toml', '**/Cargo.lock', 'rust-toolchain', 'rust-toolchain.toml') }}'
        echo "::set-output name=key::$key-${hash:0:20}"
        echo "::set-output name=restore-key::$key-"
      shell: bash
    - name: Installing sccache
      run: |
        asset_name='sccache-${{ inputs.version }}-x86_64-${{ steps.platform.outputs.platform }}'
        gh release download --repo 'mozilla/sccache' --dir '.' --pattern "$asset_name.tar.gz" '${{ inputs.version }}'
        tar -zxf "$asset_name.tar.gz"
        cp "$asset_name/sccache" '/usr/local/bin/sccache'
        chmod +x '/usr/local/bin/sccache'
        rm -r "$asset_name"
        rm "$asset_name.tar.gz"
      shell: bash
    - name: Configuring sccache environment
      run: |
        if [ -z '${{ env.RUSTC_WRAPPER }}' ]; then
          echo 'RUSTC_WRAPPER=sccache' >> $GITHUB_ENV
        fi
        if [ -z '${{ env.SCCACHE_DIR }}' ]; then
          echo "SCCACHE_DIR=$(realpath ~/.cache/sccache)" >> $GITHUB_ENV
        fi
      shell: bash
    - name: Deploying cache
      # https://github.com/actions/cache/pull/489
      # https://github.com/env0/cache
      uses: filecoin-project/cache-action@6974ff48851b8d0259af2b7a68fedd3be53ce754 
      with:
        path: |
          ${{ env.SCCACHE_DIR }}
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/bin
          ~/.cargo/.crates.toml
          ~/.cargo/.crates2.json
          ~/.cargo/git/db/
          target/
        key: ${{ steps.cache.outputs.key }}
        restore-keys: |
          ${{ steps.cache.outputs.restore-key }}
