[package]
name = "ipld_kamt-fuzz"
version = "0.0.0"
authors = ["ChainSafe Systems <info@chainsafe.io>", "Protocol Labs", "Filecoin Core Devs"]
publish = false
edition.workspace = true
license.workspace = true

[package.metadata]
cargo-fuzz = true

[dependencies]
libfuzzer-sys = { workspace = true }
arbitrary = { workspace = true, features = ["derive"] }

fvm_ipld_kamt = { workspace = true }
fvm_ipld_blockstore = { workspace = true }

[[bin]]
name = "kamt-simple"
path = "fuzz_targets/simple.rs"
test = false
doc = false
