[package]
name = "fvm-bench"
version = "0.1.0"
edition = "2021"

[dependencies]
fvm_integration_tests = { workspace = true }
fvm = { workspace = true, default-features = false }
fvm_shared = { workspace = true }
fvm_ipld_encoding = { workspace = true }
anyhow = { workspace = true }
hex = { workspace = true }
clap = { version = "4.3.9", features = ["derive", "std", "help", "usage", "error-context"], default-features = false }
env_logger = "0.11.5"
