[package]
name = "fvm-bench"
version = "0.1.0"
edition = "2021"

[dependencies]
fvm_integration_tests = { path = "../../testing/integration" }
fvm_ipld_encoding = { path = "../../ipld/encoding" }
fvm_shared = { path = "../../shared" }
anyhow = "1.0.71"
clap = { version = "4.3.9", features = ["derive", "std", "help", "usage", "error-context"], default-features = false }
hex = "0.4.3"
env_logger = "0.10.0"
fvm = { path = "../../fvm", default-features = false }
