[package]
name = "fvm_test_actors"
description = "Filecoin Virtual Machine WASM actor builder"
version = "0.1.0"
edition.workspace = true
license.workspace = true
authors = ["Protocol Labs", "Filecoin Core Devs"]
repository.workspace = true
publish = false
