[package]
name = "cgobs-example"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["staticlib"]

[dependencies]
blockstore = { version = "0.1.0", path = "../../../../lib/blockstore" }
cgobs = { path = "../../rust" }
cid = "0.7.0"

