[package]
name = "testkit"
version = "0.1.0"
edition = "2021"

[dependencies]
fvm_integration_tests = { path = "../../testing/integration" }
fvm_ipld_blockstore = { path = "../../ipld/blockstore" }
fvm_ipld_encoding = { path = "../../ipld/encoding" }
fvm_shared = { path = "../../shared" }
fvm = { path = "../../fvm", default-features = false, features = ["testing"] }

anyhow = "1.0.47"
cid = { version = "0.8.5", default-features = false }
hex = "0.4.3"
serde = { version = "1.0.148", features = ["derive"] }
