[package]
name = "ipld_hamt-fuzz"
version = "0.0.0"
authors = ["ChainSafe Systems <info@chainsafe.io>", "Protocol Labs", "Filecoin Core Devs"]
publish = false
edition = "2021"

[package.metadata]
cargo-fuzz = true

[dependencies]
libfuzzer-sys = { workspace = true }
arbitrary = { workspace = true, features = ["derive"] }

fvm_ipld_hamt = { workspace = true }
fvm_ipld_blockstore = { workspace = true }

[[bin]]
name = "hamt-simple"
path = "fuzz_targets/simple.rs"
test = false
doc = false

[[bin]]
name = "extensions"
path = "fuzz_targets/extensions.rs"
test = false
doc = false
