[package]
name = "check-license"
version.workspace = true
license.workspace = true
edition.workspace = true
repository.workspace = true
authors.workspace = true

[dependencies]
walkdir = "2.5.0"
regex = "1.11.0"
lazy_static = "1.5.0"