[package]
name = "fil_gas_calibration_actor"
version = "0.1.0"
edition = "2021"
publish = false

[target.'cfg(target_arch = "wasm32")'.dependencies]
fvm_sdk = { workspace = true }
fvm_shared = { workspace = true }
fvm_ipld_encoding = { workspace = true }
fvm_gas_calibration_shared = { workspace = true }

cid = { workspace = true }
num-derive = { workspace = true }
num-traits = { workspace = true }
serde = { workspace = true }
anyhow = { workspace = true }
libipld = { workspace = true }

[lib]
crate-type = ["cdylib"]
