[package]
name = "fil_gas_calibration_actor"
version = "0.1.0"
edition = "2021"
publish = false

[target.'cfg(target_arch = "wasm32")'.dependencies]
fvm_sdk = { workspace = true }
fvm_shared = { workspace = true }
fvm_ipld_encoding = { version = "0.4.0" }
fvm_gas_calibration_shared = { path = "../../../calibration/shared" }

cid = { workspace = true }
num-derive = "0.4"
num-traits = "0.2"
serde = { version = "1.0", features = ["derive"] }
anyhow = "1.0.71"

[lib]
crate-type = ["cdylib"]
