[package]
name = "integration_test_cases"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[workspace]
members = ["all/*"]

[dev-dependencies]
fvm = { version = "0.7.1", path = "../../fvm", default-features = false }
fvm_shared = { version = "0.6.1", path = "../../shared" }
fvm_ipld_encoding = { version = "0.2.0", path = "../../ipld/encoding" }
fvm_integration_tests = { version = "0.1.0", path = "../integration"}

anyhow = "1.0.57"
cid = { version = "0.8.2", default-features = false }
num-traits = "0.2"
serde = { version = "1.0", features = ["derive"] }
serde_tuple = "0.5"

syscall = { path = "all/syscall" }
overflow = { path = "all/overflow" }

[features]
default = ["fvm_ipld_encoding/testing"]