[package]
name = "fil_malformed_syscall_actor"
version = "0.1.0"
edition = "2021"
publish = false

[target.'cfg(target_arch = "wasm32")'.dependencies]
fvm_shared = { version = "3.1.0", path = "../../../../shared" }
fvm_sdk = { version = "3.0.0", path = "../../../../sdk" }

[lib]
crate-type = ["cdylib"] ## cdylib is necessary for Wasm build