[package]
name = "fil_readonly_actor"
version = "0.1.0"
edition = "2021"
publish = false

[target.'cfg(target_arch = "wasm32")'.dependencies]
fvm_sdk = { version = "3.3.0", path = "../../../../sdk" }
fvm_shared = { version = "3.5.0", path = "../../../../shared" }
fvm_ipld_encoding = { version = "0.4.0", path = "../../../../ipld/encoding" }
cid = { workspace = true }

[lib]
crate-type = ["cdylib"] ## cdylib is necessary for Wasm build
