[package]
name = "fil_gaslimit_actor"
version = "0.1.0"
edition = "2021"
publish = false

[target.'cfg(target_arch = "wasm32")'.dependencies]
fvm_ipld_encoding = { workspace = true }
fvm_sdk = { workspace = true }
fvm_shared = { workspace = true }
serde = { workspace = true }
serde_tuple = { workspace = true }
log = { workspace = true }

[lib]
crate-type = ["cdylib"] ## cdylib is necessary for Wasm build
