[package]
name = "fil_gaslimit_actor"
version = "0.1.0"
edition = "2021"
publish = false

[target.'cfg(target_arch = "wasm32")'.dependencies]
fvm_ipld_encoding = { version = "0.4.0" }
fvm_sdk = { workspace = true }
fvm_shared = { workspace = true }
serde = {version = "1.0.164", features = ["derive"] }
serde_tuple = "0.5.0"
log = "0.4.19"

[lib]
crate-type = ["cdylib"] ## cdylib is necessary for Wasm build
