[package]
name = "fil_hello_world_actor"
version = "0.1.0"
edition.workspace = true
publish = false
license.workspace = true

[target.'cfg(target_arch = "wasm32")'.dependencies]
fvm_sdk = { workspace = true }
fvm_shared = { workspace = true }

[lib]
crate-type = ["cdylib"] ## cdylib is necessary for Wasm build
