name: rust cache
description: Shared Compilation Cache for Rust
inputs:
  key:
    description: An additional key for the cache
    required: false
  shared-key:
    description: An additional key that is stable over multiple jobs
    required: false
runs:
  using: composite
  steps:
    - id: rust
      name: Checking Rust version
      run: |
        version="$(rustc -vV)"
        echo "::set-output name=release::$(sed -En 's/^release: (.+)/\1/p' <<< "$version")"
        echo "::set-output name=host::$(sed -En 's/^host: (.+)/\1/p' <<< "$version")"
        echo "::set-output name=commit-hash::$(sed -En 's/^commit-hash: (.{0,12}).*/\1/p' <<< "$version")"
      shell: bash
    - id: cache
      name: Computing cache key
      run: |
        key='v0'
        if [[ ! -z '${{ inputs.shared-key }}' ]]; then
          key="$key-${{ inputs.shared-key }}"
        else
          if [[ ! -z '${{ inputs.key }}' ]]; then
            key="$key-${{ inputs.key }}"
          fi
          key="$key-${{ github.job }}"
        fi
        key="$key-${{ steps.rust.outputs.release }}-${{ steps.rust.outputs.host }}-${{ steps.rust.outputs.commit-hash }}"
        hash='${{ hashFiles('**/Cargo.toml', '**/Cargo.lock', 'rust-toolchain', 'rust-toolchain.toml') }}'
        echo "::set-output name=key::$key-${hash:0:20}"
        echo "::set-output name=restore-key::$key-"
      shell: bash
    - name: Deploying cache
      uses: env0/cache@64daede5552c68991cba51f3bc0ac2bc26945a11 # https://github.com/actions/cache/pull/489
      with:
        path: |
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
          target/
        key: ${{ steps.cache.outputs.key }}
        restore-keys: |
          ${{ steps.cache.outputs.restore-key }}
