[package]
name = "fil_create_actor"
version = "0.1.0"
edition = "2021"
publish = false

[target.'cfg(target_arch = "wasm32")'.dependencies]
fvm_sdk = { workspace = true }
fvm_shared = { workspace = true }
actors_v12_runtime = { package = "fil_actors_runtime", git = "https://github.com/filecoin-project/builtin-actors", branch = "master" }

[lib]
crate-type = ["cdylib"] ## cdylib is necessary for Wasm build
