[package]
name = "fil_create_actor"
version = "0.1.0"
edition = "2021"
publish = false

[target.'cfg(target_arch = "wasm32")'.dependencies]
fvm_sdk = { version = "3.3.0", path = "../../../../sdk" }
fvm_shared = { version = "3.4.0", path = "../../../../shared" }
fvm_ipld_encoding = { version = "0.4.0", path = "../../../../ipld/encoding" }
#actors_v10_runtime = { package = "fil_actors_runtime", git = "https://github.com/filecoin-project/builtin-actors", branch = "next" }
actors_v10_runtime = { package = "fil_actors_runtime", path = "../../../../../filecoin-builtin-actors/runtime" }
serde = { version = "1.0.136", features = ["derive"] }

[lib]
crate-type = ["cdylib"] ## cdylib is necessary for Wasm build
