[package]
name = "syscall"
version = "0.1.0"
edition = "2021"

[dependencies]
fvm_sdk = { version = "0.6.1", path = "../../../../sdk" }
fvm_shared = { version = "0.6.1", path = "../../../../shared" }
fvm_ipld_encoding = { version = "0.2.0", path = "../../../../ipld/encoding" }

cid = { version = "0.8.2", default-features = false }

[build-dependencies]
wasm-builder = "3.0.1"
wasmtime = "0.33.0"
