[package]
name = "syscall"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
fvm_sdk = { version = "0.6.0", path = "../../../../sdk" }
fvm_ipld_encoding = { version = "0.1.0", path = "../../../../ipld/encoding" }
serde = { version = "1.0", features = ["derive"] }
serde_tuple = "0.5"

[dev-dependencies]
fvm_integration_tests = { version = "0.1.0", path = "../../../integration" }
fvm_shared = { version = "0.6.0", path = "../../../../shared" }
fvm = { version = "0.7.1", path = "../../../../fvm", default-features = false }
num-traits = "0.2"


[build-dependencies]
wasm-builder = "3.0.1"
wasmtime = "0.33.0"

[features]
default=["fvm_shared/testing", "fvm/testing"]